# Generated by Django 5.0.7 on 2025-10-04 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowls', '0002_comment_hidden_at_comment_hidden_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='meowl',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='meowllocation',
            options={'ordering': ['-verified_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='pointsledger',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='locationverification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='meta_json',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hidden_reason',
        ),
        migrations.RemoveField(
            model_name='meowl',
            name='archived_reason',
        ),
        migrations.RemoveField(
            model_name='meowl',
            name='status',
        ),
        migrations.RemoveField(
            model_name='meowllocation',
            name='verification_count',
        ),
        migrations.RemoveField(
            model_name='pointsledger',
            name='ref_scan',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='lng',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='meowl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meowls.meowl'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationverification',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationverification',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationverification',
            name='meowl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meowls.meowl'),
        ),
        migrations.AddField(
            model_name='meowllocation',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('comment_hide', 'Hide Comment'), ('comment_unhide', 'Unhide Comment'), ('meowl_archive', 'Archive Meowl'), ('meowl_unarchive', 'Unarchive Meowl'), ('user_promote', 'Promote User'), ('user_demote', 'Demote User'), ('scan', 'Scan'), ('create', 'Create'), ('verify', 'Verify')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_hidden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meowl',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meowls_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meowl',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meowl',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meowl',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meowls_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meowl',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='meowllocation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='meowllocation',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meowllocation',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meowllocation',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meowllocation',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('verified', 'Verified'), ('current', 'Current'), ('rejected', 'Rejected')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='pointsledger',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsledger',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scan',
            name='ip_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='scan',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='MeowlUpdate',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='locationverification',
            name='location',
        ),
    ]
