# Generated by Django 5.0.7 on 2025-10-04 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowls', '0003_remove_profile_user_alter_auditlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('comment_hide', 'Hide Comment'), ('comment_unhide', 'Unhide Comment'), ('meowl_archive', 'Archive Meowl'), ('meowl_unarchive', 'Unarchive Meowl'), ('user_promote', 'Promote User'), ('user_demote', 'Demote User'), ('user_suspend', 'Suspend User'), ('user_unsuspend', 'Unsuspend User'), ('scan', 'Scan'), ('create', 'Create'), ('verify', 'Verify')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
